In [1]:
x = ["apple",12,13,"hi"]

In [2]:
x

['apple', 12, 13, 'hi']

In [3]:
x[0]

'apple'

In [5]:
x[2]=14

In [6]:
x


['apple', 12, 14, 'hi']

In [7]:
x.reverse()


In [8]:
x


['hi', 14, 12, 'apple']

In [9]:
x.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [10]:
y = [1,2,3,4,5]

In [11]:
y.sort()

In [12]:
y


[1, 2, 3, 4, 5]

In [14]:
smaple_tupple = (1,"hi",15,(1+2j))

In [16]:
smaple_tupple

(1, 'hi', 15, (1+2j))

In [17]:
smaple_tupple[3]

(1+2j)

In [18]:
smaple_tupple[3]= 0

TypeError: 'tuple' object does not support item assignment

In [19]:
m = (1,2,3)
n = list(m)
n

[1, 2, 3]

In [20]:
n.remove(3)
n

[1, 2]

In [21]:
n.append(3)
n

[1, 2, 3]

In [22]:
setdata = {1,1,1,2,2,2,3,3,3}

In [23]:
setdata

{1, 2, 3}

In [24]:
setdata.add(4)
setdata

{1, 2, 3, 4}

In [25]:
setdata.remove(4)

In [26]:
setdata

{1, 2, 3}

In [27]:
dictionary = {1:"one",2:"two",3:"three"}
dictionary

{1: 'one', 2: 'two', 3: 'three'}

In [28]:
dictionary[1]

'one'

In [33]:
dictionary[4]="four"
dictionary

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}

In [30]:
dictionary

{1: 'one', 2: 'two', 3: 'three'}

In [34]:
a ="hi how r u"

In [35]:
a[0]

'h'

In [36]:
a[2
]

' '

In [37]:
a[2]="love"

TypeError: 'str' object does not support item assignment

In [40]:
list1 = [1,2,3]
list1.append(4)
list1

[1, 2, 3, 4]

In [41]:
#numpy

In [42]:
import numpy as np

In [43]:
simple_list=[7,9,19,11]
simple_array=np.array(simple_list)

In [44]:
simple_array

array([ 7,  9, 19, 11])

In [45]:
listoflist =([1,2,3],[4,5,6],[7,8,9])
listoflist

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [46]:
matrix=np.array(listoflist)

In [47]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [50]:
np.arange(5,28,6)

array([ 5, 11, 17, 23])

In [51]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros(7,dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [54]:
np.ones(8,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [58]:
np.eye(4,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [63]:
m=np.random.rand(4,5)

In [64]:
m

array([[0.12776914, 0.76868855, 0.24268708, 0.1225204 , 0.52854034],
       [0.81617854, 0.31103874, 0.72003834, 0.43002506, 0.50333151],
       [0.44850939, 0.21118324, 0.1425973 , 0.04343842, 0.79454411],
       [0.49879243, 0.89940331, 0.05587595, 0.00983311, 0.50349807]])

In [66]:
np.linspace(20,50,4)

array([20., 30., 40., 50.])

In [68]:
np.random.randint(20,56,100)

array([26, 27, 55, 21, 23, 26, 43, 33, 21, 23, 30, 25, 21, 25, 34, 25, 20,
       20, 36, 52, 52, 37, 26, 50, 34, 24, 27, 32, 31, 31, 36, 53, 30, 42,
       43, 28, 46, 48, 27, 30, 27, 42, 22, 45, 25, 30, 48, 47, 36, 54, 21,
       53, 23, 24, 44, 45, 49, 20, 55, 55, 53, 43, 54, 34, 47, 48, 44, 29,
       23, 34, 39, 52, 43, 20, 52, 26, 37, 28, 53, 53, 55, 24, 33, 42, 32,
       37, 47, 55, 35, 44, 55, 34, 54, 26, 38, 41, 45, 41, 27, 27])

In [69]:
np.random.randint(10,100,15)

array([41, 15, 36, 81, 34, 88, 10, 51, 87, 50, 93, 91, 71, 43, 20])

In [72]:
sample_array=np.arange(2,20,5)
sample_array

array([ 2,  7, 12, 17])

In [73]:
sample_array.min()

2

In [74]:
sample_array.argmin()

0

In [75]:
sample_array.max()

17

In [76]:
sample_array.argmax()

3

In [78]:
w=np.eye(5)
w

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
w.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
k=np.random.rand(4,5)

In [83]:
k

array([[0.77337332, 0.95256005, 0.72584257, 0.18569651, 0.81596065],
       [0.95872351, 0.25178113, 0.37442965, 0.46167424, 0.06072375],
       [0.44704474, 0.07487039, 0.55033543, 0.55615007, 0.08303145],
       [0.64236352, 0.84503493, 0.67219464, 0.02259621, 0.35492499]])

In [84]:
k.T

array([[0.77337332, 0.95872351, 0.44704474, 0.64236352],
       [0.95256005, 0.25178113, 0.07487039, 0.84503493],
       [0.72584257, 0.37442965, 0.55033543, 0.67219464],
       [0.18569651, 0.46167424, 0.55615007, 0.02259621],
       [0.81596065, 0.06072375, 0.08303145, 0.35492499]])

In [85]:
import numpy as np

In [88]:
sample_array=np.arange(10,28)

In [89]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [90]:
sample_array=sample_array.reshape(2,9)

In [91]:
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [92]:
sample_array[1]=9

In [93]:
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9]])

In [94]:
sample_array=np.arange(10,100)

In [95]:
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [97]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [98]:
subset=sample_array[0:5]

In [99]:
subset

array([10, 11, 12, 13, 14])

In [100]:
sample_array[:]=10000

In [102]:
sample_array

array([10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000,
       10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000])

In [103]:
# two dimensional array

In [104]:
import numpy as np

In [105]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
sample_matrix[0][0]

1

In [109]:
sample_matrix[:,2]

array([3, 6, 9])

In [110]:
sample_matrix[1:3,2:4]

array([[6],
       [9]])

In [112]:
sample_matrix[1:,2:]

array([[6],
       [9]])

In [113]:
sample_matrix[2]

array([7, 8, 9])

In [114]:
sample_matrix=sample_matrix+sample_matrix

In [115]:
sample_matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [116]:
np.exp(sample_matrix)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05],
       [1.20260428e+06, 8.88611052e+06, 6.56599691e+07]])

In [117]:
np.sqrt(sample_matrix)

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162],
       [3.74165739, 4.        , 4.24264069]])

In [118]:
np.log(sample_matrix)

array([[0.69314718, 1.38629436, 1.79175947],
       [2.07944154, 2.30258509, 2.48490665],
       [2.63905733, 2.77258872, 2.89037176]])